# Hello application
app:
  build: .
  ports:
    - 8000
  environment:
    SERVICE_NAME: app
    CONSUL_URL: 10.0.2.15:8500
    FILECONSUL_PREFIX: app
    FILECONSUL_BASEPATH: /app/config

# Nginx Load Balancer
lb:
  image: 1science/nginx:consul
  ports:
    - 80:80
  volumes:
    - ./lb/etc/consul-template:/etc/consul-template
  environment:
    SERVICE_NAME: load-balancer
    # Change this variable to point on your Consul
    CONSUL_URL: 10.0.2.15:8500

# Registrator to register on local Consul
registrator:
  image: gliderlabs/registrator:latest
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  # Change the command to point on your Consul
  command: consul://10.0.2.15:8500